language: node_js
node_js:
  - 10

# 指定缓存模块，可选。缓存可加快编译速度
cache:
  directories:
    - themes

# 指定仓库地址
env:
  global:
    # Github Pages
    - GITHUB_ADDR: github.com/clsss/blog.git
    # Coding Pages
    - CODING_TOKEN_NAME: DWujZUogZN
    - CODING_ADDR: e.coding.net/c_illusion/hugo_blog.git

# 指定dev分支触发钩子
branches:
  only:
    - blog # build dev branch only

before_install:
  - export TZ='Asia/Beijing' # 设置时区

# Start: Build Lifecycle
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.70.0_Linux-64bit.tar.gz
  - chmod +x hugo   # 给执行权限
  - export PATH=$PATH:$PWD
  - hugo version
  - rm -rf public
  - git log -p -2 | cat
  - commit_msg=$(git log -n1 --pretty=format:"%s")
  - echo 'install done!'

# 执行 hugo 生成静态页面
script:
  - hugo
  - echo 'Hugo build done !'

# 提交，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "c_illusion"
  - git config user.email "670199384@qq.com"
  - git add .
  - git commit -m "自动部署：${commit_msg} "
  # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_ADDR}" master:master
  # Coding Pages
  - git push --force --quiet "https://${CODING_TOKEN_NAME:${CODING_TOKEN}@${CODING_ADDR}" master:master
  # set tag
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "tag $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GITHUB_TOKEN}@${GITHUB_ADDR}" master:master --tags
  # Coding Pages
  - git push --quiet "https://${CODING_TOKEN_NAME:${CODING_TOKEN}@${CODING_ADDR}" master:master --tags
# End: Build LifeCycle
